# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f50a7fc2e4b0003e1a1aa49e6c9a78b17dad1742b0b9f238a0edcad81464e2b0c8a6d6c2aa730dd96c914e3e71fc3eb5b5330ea5cc21d2e3a39eeb9e33de89b

test:
  secret_key_base: 8741bf756d6431faec3acc78e54b01ae5e46e478167501854d11b7868832df70c8d130e0379e29276121a220aea1d0d16c6e24a47c8a73666cf6606951af30a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
